# Generated by Django 5.2.3 on 2025-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_produits_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produits',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.RenameField(
            model_name='facture_client',
            old_name='total_amond',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='produits',
            old_name='quantité',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='total_amont',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vente',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
