# Generated by Django 5.2.3 on 2025-06-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
